@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.github.ysbbbbbb.kaleidoscopecookery.crafting.serializer;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;