@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.github.ysbbbbbb.kaleidoscopecookery.compat.jei.category;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;