@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.github.ysbbbbbb.kaleidoscopecookery.datagen.lootable;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;